remote_url: "https://5a345852cae2.ngrok-free.app"
base_url: "http://localhost:8001"
from_number: "+12136957366"
to_number: "+34960324442" # 34960324442, 
test_id: "vdsxdkyzpjz7jjlbjtp8zo5h"
version_id: "hwtq29i0jrhosqpukiobu6n4"
tests: [1,2,3]
asycio_timeout: 120.0
request_timeout: 120.0
talk_timeout: 80
max_turns: 12
agent_goes_first: true

