remote_url: "https://1a648hdjdic.ngrok-free.app"
base_url: "http://localhost:8001"
from_number: "+12136957366"
to_number: "+3446879824442" # 3499364524442, 
test_id: "vs8ya5j0otyhc01fiogjvd43"
version_id: "cwbml872o0rtug17agv6sb70"
tests: [1,2,3]
asycio_timeout: 120.0
request_timeout: 120.0
talk_timeout: 80
max_turns: 12
agent_goes_first: true

