version: '3.8'

services:
  calling-agent:
    build: .
    ports:
      - "8001:8001"
    environment:
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - ELEVENLABS_API_KEY_GAL=${ELEVENLABS_API_KEY_GAL}
      - API_KEY=${API_KEY}
      - GALTEA_API_KEY_DEV=${GALTEA_API_KEY_DEV}
    env_file:
      - .env
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: calling-agent-network